# Generated by Django 6.0 on 2025-12-05 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('style_summary', models.TextField(blank=True, help_text='Aggregated style description from all assets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text="User's generation request")),
                ('output_type', models.CharField(choices=[('ui_mockup', 'UI Mockup'), ('flow_diagram', 'Flow Diagram'), ('marketing_banner', 'Marketing Banner'), ('both', 'Both UI & Flow')], default='ui_mockup', max_length=20)),
                ('num_variations', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refinement_prompt', models.TextField(blank=True, help_text='Additional refinement instructions')),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinements', to='core.generationrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='generated/%Y/%m/')),
                ('variation_number', models.PositiveIntegerField()),
                ('output_type', models.CharField(choices=[('ui_mockup', 'UI Mockup'), ('flow_diagram', 'Flow Diagram'), ('marketing_banner', 'Marketing Banner'), ('both', 'Both UI & Flow')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (dimensions, format, etc.)')),
                ('consistency_score', models.FloatField(blank=True, help_text='AI-scored style consistency (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.generationrequest')),
            ],
            options={
                'ordering': ['variation_number'],
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='assets/%Y/%m/')),
                ('asset_type', models.CharField(choices=[('ui_screenshot', 'UI Screenshot'), ('style_guide', 'Style Guide'), ('brand_image', 'Brand Image'), ('marketing', 'Marketing Material'), ('other', 'Other')], default='ui_screenshot', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('extracted_style', models.JSONField(blank=True, default=dict, help_text='Structured style data extracted by AI')),
                ('extracted_description', models.TextField(blank=True, help_text='Human-readable style description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('content', models.TextField(blank=True, help_text='For pasted text content')),
                ('doc_type', models.CharField(choices=[('spec', 'Feature Specification'), ('guideline', 'UX/UI Guideline'), ('requirements', 'Requirements Document'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='AI-extracted key points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
